// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdFoQgRznP32G4hsfInZztOAYkTaQxRIA',
    appId: '1:18950016683:web:f8eb2ac412ae7392a731ee',
    messagingSenderId: '18950016683',
    projectId: 'rrd-app',
    authDomain: 'rrd-app.firebaseapp.com',
    storageBucket: 'rrd-app.firebasestorage.app',
    measurementId: 'G-3434ZXLK96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaFgrxN-K1EH3vhSD7jiH3TvUcIyRErkY',
    appId: '1:411373140220:android:d0135f9c9c4781695eff79',
    messagingSenderId: '411373140220',
    projectId: 'rhino-rakt-donors',
    storageBucket: 'rhino-rakt-donors.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-NXhORVnXRnFDnkbXz255HEpsB-GHb0Q',
    appId: '1:411373140220:ios:e84174860f84ad065eff79',
    messagingSenderId: '411373140220',
    projectId: 'rhino-rakt-donors',
    storageBucket: 'rhino-rakt-donors.firebasestorage.app',
    iosBundleId: 'com.rhinorakt.donor',
  );

}